language: sh

before_script:
  - wget "https://cli.run.pivotal.io/stable?release=debian64&version=6.21.1&source=github-rel" -O cli.deb
  - sudo dpkg -i cli.deb
  - sudo apt-get install -y python-virtualenv

script:
  - cd tests && bash run.sh

notifications:
  email: false
